POST http://localhost:3333/events
Content-Type: application/json

{
    "title": 123,
    "details": "Um evento para quem é apaixonado por programação",
    "maximumAttendees": 150
}

###

POST http://localhost:3333/events/b223d32f-075e-4d28-b309-a835743424cf/attendees
Content-Type: application/json

{
    "name": "Isabela de Camargo",
    "email": "isabela@teste.com"
}

###

GET http://localhost:3333/events/b223d32f-075e-4d28-b309-a835743424cf

###

GET http://localhost:3333/attendees/4/badge

###

GET http://localhost:3333/attendees/2/check-in

###

GET http://localhost:3333/events/b223d32f-075e-4d28-b309-a835743424cf/attendees